### ISSUE TITLE
Custom YAML tags

### ISSUE THREAD

**Issue by medihack** [remcohaszing/monaco-yaml#102]
In my YAML document, I want to use some custom tags. Unfortunately, when using monaco-yaml I get the error marker that the tag is unknown (e.g. `unknown tag <!foo>YAML(0)`). Is it possible somewhere to define those custom tags or to disable tag validation at all (without disabling validation as a whole)?

**Comment by medihack** [comment]
I just found out that it is already supported by the `yaml-language-server` using the [`customTags`](https://github.com/redhat-developer/yaml-language-server/blob/main/src/languageservice/yamlLanguageService.ts#L73) option. I guess it could then be easily added as another option for `setDiagnosticsOptions`. If you are interested then I could come up with a pull request.

**Comment by remcohaszing** [comment]
This was added in #103
