### ISSUE TITLE
validation for if-then-else schema feature is not correct

### ISSUE THREAD

**Issue by delaprada** [remcohaszing/monaco-yaml#104]
Hello, I want to use this JSON schema feature in my project: https://json-schema.org/understanding-json-schema/reference/conditionals.html?highlight=options#if-then-else.

![image](https://user-images.githubusercontent.com/40078051/133052864-50f5938d-32a2-4b98-aba4-6a9f69e5c2b2.png)

But when I apply it to my schema:

```
// add the following attribute for testing
"p3": {
  "type": "object",
  "properties": {
    "street_address": {
      "type": "string"
    },
    "country": {
      "default": "United States of America",
      "enum": ["United States of America", "Canada"]
    }
  },
  "if": {
    "properties": { "country": { "const": "United States of America" } }
  },
  "then": {
    "properties": { "postal_code": { "pattern": "[0-9]{5}(-[0-9]{4})?" } }
  },
  "else": {
    "properties": { "postal_code": { "pattern": "[A-Z][0-9][A-Z] [0-9][A-Z][0-9]" } }
  }
},
```

The validation is not correct and the completion is not working:
![image](https://user-images.githubusercontent.com/40078051/133053291-8bc282b4-7747-42bb-8429-db9d5becd58d.png)

Can monaco-yaml suport this feature?

**Comment by remcohaszing** [comment]
Based on your partial code sample, it looks like `p3` is a property of an object inside a list whose value should be an object. However, the value in your example looks like:

```yaml
- n1:
    type: foo
    p3:
      country
```

which is equivalent to:

```yaml
- n1:
    type: foo
    p3: 'country'
```

So validation is working correctly.

Actual validation happens in `yaml-language-server`, also known for powering the VSCode YAML extension. I believe `if-then-else` is supported. If it works in VS Code, then it works in `monaco-yaml`.

**Comment by delaprada** [comment]
Thank you so much. Maybe it's not the problem of `monaco-yaml`.  The support for `if-then-else` in monaco editor is not good enough.
