### ISSUE TITLE
Crash caused if navigating too quickly away from editor

### ISSUE THREAD

**Issue by patrickshipe** [remcohaszing/monaco-yaml#106]
https://github.com/remcohaszing/monaco-yaml/blob/8d278d3d19e3c7cfca6a4dd8cbe370ccb1798310/src/languageFeatures.ts#L65

If the user navigates away from an editor before this promise resolves, `editor.getModel(resource)` will return `null` and cause a crash. We can avoid this by changing to 

```ts
    if (model && model.getModeId() === languageId) {
      editor.setModelMarkers(model, languageId, markers);
    }
```

**Comment by remcohaszing** [comment]
Thanks for pointing this out!

I think it should also be possible for `doValidate()` to accept a model. Then the call to `editor.getModel()` could be avoided entirely meaning the model would never be `null` and the `model.getModeId() === languageId` check becomes redundant.

I need to investigate this though.

**Comment by patrickshipe** [comment]
Thank you @remcohaszing  - I created this PR to match what `monaco-json` does to fix the immediate crash issue: https://github.com/remcohaszing/monaco-yaml/pull/110

Feel free to use as you wish :)
