### ISSUE TITLE
monaco-yaml version 3.2.0 has no validation function

### ISSUE THREAD

**Issue by delaprada** [remcohaszing/monaco-yaml#108]
I use version 3.1.0 before and the yaml editor worked well. It had validation and completion function:
![image](https://user-images.githubusercontent.com/40078051/133396886-5f751ac8-bbbd-48e9-b33a-d526fb044e0d.png)

When I update to version 3.2.0, the validation and completion function doesn't work:
![image](https://user-images.githubusercontent.com/40078051/133397712-35419207-649b-4494-bd56-228c9bf97a0d.png)

**Comment by remcohaszing** [comment]
Thanks for reporting this! I think it might be related to #105

Does your code call `setDiagnosticsOptions` in a dynamic context? I.e. in a dynamically imported module or inside a Angular/React component, etc.?

Also, do you have a stack trace?

**Comment by delaprada** [comment]
Yes, I use `setDiagnosticsOptions` inside a React project.

Maybe the example in this issue: #92 can be helpful.

**Comment by remcohaszing** [comment]
> Yes, I use `setDiagnosticsOptions` inside a React project.

Thanks, that’s useful information :smile: 

> Maybe the example in this issue: #92 can be helpful.

It’s different, since in that example `setDiagnosticsOptions` is called outside of the component.

---

I intend to fix this soon, when I have time. Until then, I suggest using `3.1.0`.

**Comment by delaprada** [comment]
Sorry, in my project, `setDiagnosticsOptions` is called outside of the  react component too although it is used in a react project.
Thank you very much and look forward to the subsequent updates.

**Comment by remcohaszing** [comment]
Could you try v3.2.1? I think should be fixed.

**Comment by delaprada** [comment]
Yes, v3.2.1 works well. Thank you ☺️.
