### ISSUE TITLE
Can not run example or use it with vite

### ISSUE THREAD

**Issue by YunYouJun** [remcohaszing/monaco-yaml#115]
## Main Problem

> `monaco-yaml@3.2.1`

Like https://github.com/remcohaszing/monaco-yaml/issues/53, i can not run it with vite.

I also get `Unpected usage at EditorSimpleWorker.loadForeignModule`.

![image](https://user-images.githubusercontent.com/25154432/133807294-04b302d4-6cba-4eb9-8b82-bd7043129002.png)

### about `package-lock.json`

Otherwise, i tried to run example in this repo. 

This repo has `package-lock.json`, so i use `npm` to install it. But `yaml-language-server` told me only use `yarn`.

> I find https://github.com/redhat-developer/yaml-language-server/pull/528, but it has not been released.

So, can we remove `package-lock.json` to avoid forcing `npm`?

### Can not run example

I remove package-lock.json and use yarn to run it. (I tried `npm` too.)

```bash
yarn prepack
// to get built esm
cd examples/demo && yarn start
```

The example can not show validate tooltip like https://monaco-yaml.js.org/.

![image](https://user-images.githubusercontent.com/25154432/133808972-7fe2cd9f-a78d-4883-a4a6-d381fd1b6e5c.png)

Can you help me?

> Thanks. I have tried every method I could think of, but it didn't work.

**Comment by remcohaszing** [comment]
> ## Main Problem
> > `monaco-yaml@3.2.1`
> 
> Like #53, i can not run it with vite.
> 
> I also get `Unpected usage at EditorSimpleWorker.loadForeignModule`.
> 
> ![image](https://user-images.githubusercontent.com/25154432/133807294-04b302d4-6cba-4eb9-8b82-bd7043129002.png)

#116 contains a working vite example. I’m going to update the various examples to contain more accurate descriptions on how to get started running the examples.

> ## Other
> ### about `package-lock.json`
> Otherwise, i tried to run example in this repo.
> 
> This repo has `package-lock.json`, so i use `npm` to install it. But `yaml-language-server` told me only use `yarn`.
> 
> > I find [redhat-developer/yaml-language-server#528](https://github.com/redhat-developer/yaml-language-server/pull/528), but it has not been released.
> 
> So, can we remove `package-lock.json` to avoid forcing `npm`?

This only shows a warning, not an error. Using `npm` doesn’t cause any issues.

> ### Can not run example
> I remove package-lock.json and use yarn to run it. (I tried `npm` too.)
> 
> ```shell
> yarn prepack
> // to get built esm
> cd examples/demo && yarn start
> ```
> 
> The example can not show validate tooltip like https://monaco-yaml.js.org/.
> 
> ![image](https://user-images.githubusercontent.com/25154432/133808972-7fe2cd9f-a78d-4883-a4a6-d381fd1b6e5c.png)
> 
> Can you help me?
> 
> > Thanks. I have tried every method I could think of, but it didn't work.

Dependency management for this package is relatively fragile. You should really stick with npm when working in this repository, so the lockfile is respected.

---

> UPDATE: This config is now working for me, and might help you if you urgently need a workaround:
> 
> ```ts
> // vite.config.ts
> export default defineConfig({
>   optimizeDeps: {
>     include: ["yaml-ast-parser-custom-tags", "js-yaml"],
>   },
> });
> ```
> 
> I had some similar problems with other dependencies that exposed CJS where Vite expected ESM. `include` forces these deps to be pre-bundled, and the pre-bundling process converts them from CJS to ESM. The new version of js-yaml, whenever this lib updates, should be fine -- `yaml-ast-parser-custom-tags` may need someone to update it.

#116 shows no special configuration is necessary. I’m not very familiar with vite or your project setup, but maybe your own configuration causes some conflicts.. It just works with `js-yaml` and `yaml-ast-parser-custom-tags` Beware the upcoming version `4.0.0` replaces both `js-yaml` and `yaml-ast-parser-custom-tags` with `yaml`.

**Comment by remcohaszing** [comment]
I did add an [FAQ](https://github.com/remcohaszing/monaco-yaml#faq) section to the readme. This should help troubleshoot the issues you’re having.
