### ISSUE TITLE
Autocompletion from schema crash with large file?

### ISSUE THREAD

**Issue by anisite** [remcohaszing/monaco-yaml#122]
Hi, before v3 everything was working great, now I got a Range error :

![image](https://user-images.githubusercontent.com/3194288/135699419-52c38511-46f1-4a52-aa2d-0bf407114660.png)

This happens on an autocompletion (ex: pressing CTRL+ SPACE after "type:" element to get values)

Cause drop menu to show wrong values : 
![image](https://user-images.githubusercontent.com/3194288/135699486-1d8d55b0-1695-4e46-9010-99f36442149d.png)

Working example with v 2.5.0 
![image](https://user-images.githubusercontent.com/3194288/135699512-04cc55ae-8cc6-47cc-bd9f-3e633c728b41.png)

example large file with schema : https://raw.githubusercontent.com/TrucsPES/TestsVue/main/FRW.PR.EXTRA/schemas/3003.ecsform.yml

**Note, if I delete arround half content, everything work great... ? I can't find why :(

thanks for your time! Great project! YAML is the future 👍

**Comment by yazaabed** [comment]
> Thanks for reporting this! This is definitely a bug.
> 
> I looked into it a bit, but I’m clueless where this is coming from. I’d appreciate any help with this. Please let me know if you want to look into this and need any information.

It is not reproducible! Maybe it is only on a specific yaml? Or maybe a specific json schema. And by looking at our code it is not possible to have -1 on range 🤔 maybe it is a yaml language server issue.

**Comment by anisite** [comment]
@yazaabed everything is good if I cut half the file, you can try to paste my yaml and schema reference in a new instance of monaco yaml, everything work great with yaml language server in VS code and everything work great in old version of monaco-yaml

**Comment by remcohaszing** [comment]
I am able to reproduce this using the following steps:

1. Visit https://monaco-yaml.js.org and open the browser console
2. Replace all content with the content found in https://raw.githubusercontent.com/TrucsPES/TestsVue/main/FRW.PR.EXTRA/schemas/3003.ecsform.yml
3. On line 2886, press <kbd>Ctrl</kbd>+<kbd>Space</kbd>

I am not able to reproduce this in VS Code.

**Comment by remcohaszing** [comment]
@anisite The link  you provided for the huge YAML file no longer works. Could you update it? Allternatively you could add it as an attachment.

**Comment by aerialist7** [comment]
Hi @remcohaszing, I'm facing the same problem

![monaco-yaml-bug](https://user-images.githubusercontent.com/32072831/180388496-0dd31f36-0d31-4862-9e31-e57adaba20e5.gif)

Is there any solution or WA?

**Comment by aerialist7** [comment]
@remcohaszing, could you please help?

**Comment by remcohaszing** [comment]
This appears to have been fixed somehow.
