### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by medihack** [remcohaszing/monaco-yaml#124]
There seem to be some wrong syntax highlighting when for example entering
```
foo: "{bar: 7}"
```
`monaco-yaml` does highlight `{bar` the same way as `foo`. It should better respect that it is part of a string. Just tested the same with the YAML extension of VS Code and it doesn't have this problem.

**Comment by remcohaszing** [comment]
Nice find! Thank for reporting this, but this isn’t an issue with `monaco-yaml`. Syntax highlighting for Monaco is done by `monaco-editor` itself instead. The bug can reproduced by going to https://microsoft.github.io/monaco-editor/playground.html and copy-pasting the following code snippet into the editor:

```js
monaco.editor.create(document.getElementById("container"), {
    value: 'foo: "{bar: 7}"\n',
    language: 'yaml'
});
```

Please open an issue on https://github.com/microsoft/monaco-editor/issues instead.

**Comment by medihack** [comment]
Ok, thanks. Good to know. I opened an issue there https://github.com/microsoft/monaco-editor/issues/2681

**Comment by medihack** [comment]
Do you maybe know where the file/source code for the syntax highlighting of YAML is originated? I could try to fix it, but I don't know much about the structure of Monaco. As far as I know, it just reuses the VS Code source code, but I then wonder why my installed VS Code instance doesn't have this problem.
