### ISSUE TITLE
Document symbol doesn't expose the detail property upstream

### ISSUE THREAD

**Issue by sylven32** [remcohaszing/monaco-yaml#137]
yaml-language-server computes document symbols of YAML properties with a detail field containing the property value.
This information is not exposed upstream by monaco-yaml.
See https://github.com/remcohaszing/monaco-yaml/blob/545e6a6bc443b5c96db7b7d2e06a0dbc1967771a/src/languageFeatures.ts#L344
A change to:

```
  detail: item.detail,
```

appears to fix it.

Our use-case is following what is described in response to https://github.com/remcohaszing/monaco-yaml/issues/41, i.e. we're making use of getDocumentSymbols() undocumented API.

**Comment by remcohaszing** [comment]
Thanks for reporting this! I’ll gladly fix this, or even better, accept a pull request. :)

**Comment by sylven32** [comment]
Thanks for the prompt reply.
Here is the PR: https://github.com/remcohaszing/monaco-yaml/pull/138
