### ISSUE TITLE
Maybe need to lock the version of monac-editor?

### ISSUE THREAD

**Issue by DarknessChaser** [remcohaszing/monaco-yaml#148]
When I install monaco-yaml@ 3.2.1 by npm at 2022/2/10
```sh
npm i monaco-yaml@^3.2.1
```
monaco-editor@0.32.1 will be installed.
But the correct version seems to be monaco-editor@0.27.0.

**Comment by DarknessChaser** [comment]
Now I can solve it by executing
```sh
npm i monaco-editor@^0.27.0
```

**Comment by remcohaszing** [comment]
Minor `monaco-editor` releases are frequent and tend to contain small breaking changes. Indeed as you pointed out, `monaco-editor` 0.28.0 contains a breaking change which affected `monaco-yaml`.

I’m working on a new version of `monaco-yaml` which contains some small breaking changes. This version is compatible with `monaco-editor` 0.28.0 and greater.

You can install `monaco-yaml@4.0.0-alpha.0`. Its only breaking change is to support of `monaco-editor` 0.28.0 and greater. Future prerelease versions may contain more breaking changes though.

**Comment by DarknessChaser** [comment]
> Minor `monaco-editor` releases are frequent and tend to contain small breaking changes. Indeed as you pointed out, `monaco-editor` 0.28.0 contains a breaking change which affected `monaco-yaml`.
> 
> I’m working on a new version of `monaco-yaml` which contains some small breaking changes. This version is compatible with `monaco-editor` 0.28.0 and greater.
> 
> You can install `monaco-yaml@4.0.0-alpha.0`. Its only breaking change is to support of `monaco-editor` 0.28.0 and greater. Future prerelease versions may contain more breaking changes though.

thanks for your work,. 

Maybe with a little change, the user experience can be improved?
To be honest, it took me quite a while to find out that the version of monaco-editor was wrong.

from
```JSON
"peerDependencies": {
    "monaco-editor": ">=0.22"
  },
```

to
```JSON
"peerDependencies": {
    "monaco-editor": ">=0.27.0<0.28.0"
  },
```
