### ISSUE TITLE
(pre)release for vite support

### ISSUE THREAD

**Issue by squeedee** [remcohaszing/monaco-yaml#150]
HI! I wanted to use vite to load monaco-yaml into my product, and unfortunately i can't use a github reference to your latest code because (I suspect) the library has to be packaged up for the exports to work properly. 

I was wondering if you could cut a pre release with vite support?

**Comment by remcohaszing** [comment]
You’re absolutely right it’s time for a release. I just released [v4.0.0-alpha.1](https://github.com/remcohaszing/monaco-yaml/releases/tag/v4.0.0-alpha.1).

As far as I know, this version works with Vite. I myself am in the process of converting a dependant project from Webpack to Vite, so this is priority for me too. :smile: 

You might be interested in https://github.com/vitejs/vite/issues/6918.

**Comment by squeedee** [comment]
Thank you!

**Comment by squeedee** [comment]
Still struggle to use it. Here's my repo, pointing to the alpha.1 version https://github.com/squeedee/monaco-yaml-vite-test/blob/main/README.md

I do not see any of the errors below when I build monaco-yaml and copy the bundled objects into my app.

errors in the browser: 
```
simpleWorker.js:20 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
logOnceWebWorkerWarning @ simpleWorker.js:20
(anonymous) @ defaultWorkerFactory.js:101
error (async)
(anonymous) @ defaultWorkerFactory.js:71
Promise.then (async)
WebWorker @ defaultWorkerFactory.js:65
create @ defaultWorkerFactory.js:100
SimpleWorkerClient @ simpleWorker.js:206
_getOrCreateWorker @ editorWorkerServiceImpl.js:349
_getProxy @ editorWorkerServiceImpl.js:359
_getForeignProxy @ webWorker.js:36
getProxy @ webWorker.js:60
getClient @ index.js:395
(anonymous) @ index.js:400
doValidate @ index.js:64
onModelAdd @ index.js:81
fire @ event.js:424
createModel @ modelServiceImpl.js:333
doCreateModel @ standaloneCodeEditor.js:329
createTextModel @ standaloneCodeEditor.js:323
createModel @ standaloneEditor.js:93
(anonymous) @ index.js:66
simpleWorker.js:22 undefined
logOnceWebWorkerWarning @ simpleWorker.js:22
(anonymous) @ defaultWorkerFactory.js:101
error (async)
(anonymous) @ defaultWorkerFactory.js:71
Promise.then (async)
WebWorker @ defaultWorkerFactory.js:65
create @ defaultWorkerFactory.js:100
SimpleWorkerClient @ simpleWorker.js:206
_getOrCreateWorker @ editorWorkerServiceImpl.js:349
_getProxy @ editorWorkerServiceImpl.js:359
_getForeignProxy @ webWorker.js:36
getProxy @ webWorker.js:60
getClient @ index.js:395
(anonymous) @ index.js:400
doValidate @ index.js:64
onModelAdd @ index.js:81
fire @ event.js:424
createModel @ modelServiceImpl.js:333
doCreateModel @ standaloneCodeEditor.js:329
createTextModel @ standaloneCodeEditor.js:323
createModel @ standaloneEditor.js:93
(anonymous) @ index.js:66
simpleWorker.js:22 undefined
logOnceWebWorkerWarning @ simpleWorker.js:22
(anonymous) @ editorWorkerServiceImpl.js:360
Promise.then (async)
_getProxy @ editorWorkerServiceImpl.js:359
_getForeignProxy @ webWorker.js:36
getProxy @ webWorker.js:60
getClient @ index.js:395
(anonymous) @ index.js:400
doValidate @ index.js:64
onModelAdd @ index.js:81
fire @ event.js:424
createModel @ modelServiceImpl.js:333
doCreateModel @ standaloneCodeEditor.js:329
createTextModel @ standaloneCodeEditor.js:323
createModel @ standaloneEditor.js:93
(anonymous) @ index.js:66
editorSimpleWorker.js:460 Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:31)
    at webWorker.js:38:30
loadForeignModule @ editorSimpleWorker.js:460
(anonymous) @ webWorker.js:38
await in (anonymous) (async)
onModelAdd @ index.js:81
fire @ event.js:424
createModel @ modelServiceImpl.js:333
doCreateModel @ standaloneCodeEditor.js:329
createTextModel @ standaloneCodeEditor.js:323
createModel @ standaloneEditor.js:93
(anonymous) @ index.js:66
errors.js:8 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:31)
    at webWorker.js:38:30
    at errors.js:8:27
(anonymous) @ errors.js:8
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:6
onUnexpectedExternalError @ errors.js:25
onUnexpectedExternalError @ errors.js:39
Promise.then (async)
(anonymous) @ getLinks.js:123
getLinks @ getLinks.js:122
(anonymous) @ links.js:184
createCancelablePromise @ async.js:31
(anonymous) @ links.js:184
(anonymous) @ links.js:20
__awaiter36 @ links.js:16
beginCompute @ links.js:172
onModelChanged @ links.js:162
(anonymous) @ links.js:145
fire @ event.js:424
StandaloneEditor2 @ standaloneCodeEditor.js:199
(anonymous) @ standaloneEditor.js:62
withAllStandaloneServices @ standaloneEditor.js:49
create @ standaloneEditor.js:61
(anonymous) @ index.js:64
DevTools failed to load source map: Could not load content for http://localhost:3000/node_modules/monaco-yaml/yaml.worker.js.map: Fetch through target failed: Session is unregistering, can't dispatch pending call to Network.loadNetworkResource; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by remcohaszing** [comment]
I’ve taken a quick look and it appears the issue is unrelated to `monaco-yaml`. The example repository shows that not only the worker of `monaco-yaml` fails to load, but also `editor.worker` from Monaco Editor itself. I don’t see what’s wrong, but I suggest to try and get that project working without errors without `monaco-yaml` first, then try to reintroduce `monaco-yaml`.

**Comment by squeedee** [comment]
If i remove monaco-yaml the editor worker loads fine. But then, the same is true if I load the monaco-yaml worker. It's only when I _import_ the root "monaco-yaml" that the errors occur.

See this commit:
https://github.com/squeedee/monaco-yaml-vite-test/commit/6624de734096980c25cc5bad75c64e1c03c8e3ff#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R3-R4

**Comment by remcohaszing** [comment]
No problem! I would like it to just work as well.

Can you get schema validation working for JSON? The main difference between JSON and YAML integration is that JSON is builtin to Monaco editor by default. If that works without any errors in the console, it should work for YAML too, or at least it’s something I can help troubleshoot.

I find it really strange your simple test repo doesn’t work, but the example inside the `monaco-yaml` repo does.

**Comment by squeedee** [comment]
I have monaco yaml working in a more complex tool that I'm building, with schema validation for yaml (have not bothered with json). I've done so by packaging monaco-yaml and copying it into the project:  https://github.com/vmware-tanzu/cartographer/tree/experiment/live-editor/experimental/live-editor (see src/monaco-yaml)

If you would like to see the editor in action: https://deploy-preview-639--elated-stonebraker-105904.netlify.app/live-editor/. (I'll be posting this as a blog post to the cartographer.sh site soon, at which point this link will evaporate)

**Comment by remcohaszing** [comment]
So you literally built `monaco-yaml` from the source repository using `npm run prepack` and copied the output into your own repository? I’m glad it’s working for you, but it is strange.

What might also work is if you replace it with `monaco-yaml` as a dependency again, but instead of importing `monaco-yaml/yaml.worker?worker`, you replace it with a new file that imports `monaco-yaml/yaml.worker`.

```diff
  import App from './App.svelte'
- import {setDiagnosticsOptions} from "./monaco-yaml";
- import YamlWorker from './monaco-yaml/yaml.worker?worker';
+ import {setDiagnosticsOptions} from "monaco-yaml";
+ import YamlWorker from './lib/workaround-yaml.worker';
  import TsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';
  import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
  import {schema} from "./lib/monaco/schema";
  import AddSupplyChainLang from "./lib/monaco/supply-chain-lang";
  import "./app.css"
```

Where `lib/workaround-yaml.worker` only contains the following line:

```ts
import 'monaco-yaml/yaml.worker.js'
```

**Comment by squeedee** [comment]
> So you literally built monaco-yaml from the source repository using npm run prepack and copied the output into your own repository? I’m glad it’s working for you, but it is strange.
Correct. Works fine that way.

I'll try your suggestion.

**Comment by squeedee** [comment]
Your suggestion works: https://github.com/squeedee/monaco-yaml-vite-test/commit/185ed03c89dee2e892bdd3632d909521316f7944

That's pretty weird. I can't pretend to imagine what's happening here. But I'll leave that repo around if it helps you deal with Vite upstream.

**Comment by YunYouJun** [comment]
Can you write https://github.com/remcohaszing/monaco-yaml/issues/150#issuecomment-1048599960 in `examples/vite-example`?

It's so magic! 🤣

**Comment by remcohaszing** [comment]
@YunYouJun You are absolutely right! :magic_wand: 

I added an entry to the FAQ to explain this.

**Comment by HerringtonDarkholme** [comment]
Hi, I ran the example in `example/vite-example` but still found the foreignWorker issue. 
This only happens when the yaml document matches the schema definition and monaco-yaml tries to load schema.

<img width="566" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/2883231/205ce97b-2b36-4934-803e-85deaf2c81cc">

**Comment by YunYouJun** [comment]
> Hi, I ran the example in `example/vite-example` but still found the foreignWorker issue. This only happens when the yaml document matches the schema definition and monaco-yaml tries to load schema.
> 
> <img alt="image" width="566" src="https://user-images.githubusercontent.com/2883231/273104734-205ce97b-2b36-4934-803e-85deaf2c81cc.png">

There are some changes to the v5 api, which you can see here.

https://github.com/remcohaszing/monaco-yaml/releases/tag/v5.0.0

**Comment by HerringtonDarkholme** [comment]
@YunYouJun thanks for the direction! I have figured out the issue I have is that I have to create an indirection file for schema usage.

Say `workaround.js`, the content is simply:

```js
import 'monaco-yaml/yaml.worker.js'
```

Usage is also simple
```js
import yamlWorker from './workaround?worker'
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker'

  self.MonacoEnvironment = {
    getWorker(_: any, label: string) {
      if (label === 'yaml') {
        return new yamlWorker()
      }
      return new editorWorker()
    }
  }

```

This ESM voodoo somehow work around the unexpected usage issue.

**Comment by YunYouJun** [comment]
You're right, I've solved similar problems this way before. The v5 api is another issue.

https://github.com/YunYouJun/web-resume/blob/4d57302bf652e8a5f895a362e4543f8334e40a45/src/monaco/workaround-yaml.worker.js#L1
