### ISSUE TITLE
Incorrect work monaco-yaml in  mode local development with use vite.

### ISSUE THREAD

**Issue by yura007rt** [remcohaszing/monaco-yaml#158]
Hello! I tried use your plugin for monaco, but I encountered an error during local development. 
I copied your example with use vite and change dependence for  **"monaco-yaml": "file:../.."-->"monaco-yaml": "4.0.0-alpha.1"**. 
You can see my project https://github.com/yura007rt/monaco-yaml-example.
If I tried start task **'start'**, I get error in console _(see screenshot)_ and hints won't work
![image](https://user-images.githubusercontent.com/35426188/161222317-888ce700-963f-4e24-a5fb-7166aacc617f.png)

If I tried start task **'preview'**, monaco-yaml work correct.
![image](https://user-images.githubusercontent.com/35426188/161223391-30bae702-bc0c-457a-bb81-6434c7a5b46a.png)

I used
[NodeJS](https://nodejs.org/) >16 or higher
[npm](https://github.com/npm/cli) 8.1.2 or higher
Can you help me, that monaco yaml work in local development mode?

**Comment by remcohaszing** [comment]
I’ve seen this issue before, but don’t really understand it myself. I do know a workaround. Could you try and review the workaround I added in #159?

**Comment by yura007rt** [comment]
I used WA, but it don't work for me. I got errors in console
I updated project with WA https://github.com/yura007rt/monaco-yaml-example
![image](https://user-images.githubusercontent.com/35426188/161249981-50398a7e-9b8e-4ba6-9838-7832ae7fd536.png)

**Comment by remcohaszing** [comment]
Sorry, my bad: the `?worker` postfix is necessary for the import. I added this in #159.

You really only need to add `import 'monaco-yaml/yaml.worker.js'` to that file. It doesn’t export anything.

Also: What is _WA_? :sweat_smile:

**Comment by yura007rt** [comment]
"WA" - it is a workaround:D. This fix https://github.com/remcohaszing/monaco-yaml/pull/159 don't work for me(((
![image](https://user-images.githubusercontent.com/35426188/161261278-a7fae8b7-a922-48ab-bf9f-13905ca96896.png)
![image](https://user-images.githubusercontent.com/35426188/161261313-15e0aa26-9ebe-46f6-9683-2674c2c053a4.png)
Maybe I'm doing something wrong?

**Comment by yura007rt** [comment]
I understood! Thanks!!!

**Comment by remcohaszing** [comment]
You need to add `?yaml.worker.js` to your worker import:

```diff
  import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker'
- import YamlWorker from './yaml.worker.js';
+ import YamlWorker from './yaml.worker.js?worker';

```

**Comment by remcohaszing** [comment]
@yura007rt awesome! Also thanks for mentioning this here. I hope this helps some more people. :heart: 

I’m personally not a fan of using a special build tool just to support one library, although admittedly my own soludion isn’t that elegant either.

Anyway, I’m glad this works for you! If you want, I’ll gladly accept a pull request that adds an example for this. You could copy the [vite-example](https://github.com/remcohaszing/monaco-yaml/tree/main/examples/vite-example) as a starting point.

Just a side note: My guess is the line `languageWorkers: ['editorWorkerService']` can be omitted.
