### ISSUE TITLE
How can I use monaco yaml plugin with Monaco Editor Webpack Loader Plugin?

### ISSUE THREAD

**Issue by golergka** [remcohaszing/monaco-yaml#173]
I have ESM version of Monaco set up using the Webpack Loader plugin. I want to add monaco yaml plugin, and I struggle to understand how do I do that. I'm using the [Integrating the ESM version of the Monaco Editor](https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md) guide and [Monaco Yam plugin README](https://github.com/remcohaszing/monaco-yaml/blob/main/README.md).

The documentation on yaml plugin says to set up `getWorker` function in `MonacoEnvironment; however, the ESM documentation says to either use Webpack loader, or to set up `getWorkerUrl` function, so three different ways to set this up in total.

* The names of `getWorker` and `getWorkerUrl` functions hint that they are interchangeable — are they? Who calls these functions?
* `getWorkerUrl` uses `./ts.worker.bundle.js` for typescript, whereas `getWorker` uses `monaco-editor/esm/vs/language/typescript/ts.worker` url to create typescript worker. These urls seem very similar. Is there 1-to-1 relationship here, and what is it? If there is, where is the `monaco-editor/esm/vs/language/typescript` prefix added?
* Monaco Yaml `getWorker` function source uses `monaco-yaml/yaml.worker` url for the plugin. If urls in `getWorkerUrl` are automatically added `monaco-editor/...` prefixes, how can I use `getWorkerUrl` function with this url?
* Options for Monaco Webpack plugin aren't documented, so I'm trying to understand their meaning from types. There's `IFeatureDefinition` with `label`, `entry`, `worker` of type `IWorkerDefinition`, which in turn also has `id` and `string`. How do all of these properties relate to the `getWorkerUrl` parameters of `moduleId` and `label` (is that the label of a feature or a worker? What's the difference?) and the return value of url?
* What's the easiest and most reliable way to check if monaco yaml plugin has been successfully loaded by the editor?

Overall, there's no proper information about exact contracts of all this configuration, just simple examples, and a lot of things that seem to be vaguely similar between all the three methods (`getWorker`, `getWorkerUrl` and `MonacoWebpackPlugin`) without any clarifications, so I just feel very confused by it. These questions are my best attempt at structuring all the information available to me.

**Comment by domsew** [comment]
You may look at [this ](https://github.com/remcohaszing/monaco-yaml/tree/main/examples/monaco-editor-webpack-plugin) or [this](https://github.com/domsew/monaco-yaml/tree/esm/examples/esm-build). Let me know whether it helped.

**Comment by golergka** [comment]
> You may look at [this ](https://github.com/remcohaszing/monaco-yaml/tree/main/examples/monaco-editor-webpack-plugin) or [this](https://github.com/domsew/monaco-yaml/tree/esm/examples/esm-build). Let me know whether it helped.

Thanks, the example helped. But after I got my project working, I still feel that I don't understand why it works.

https://github.com/remcohaszing/monaco-yaml/blob/main/examples/monaco-editor-webpack-plugin/webpack.config.js#L21-L27

Where does id `monaco-yaml/yamlWorker` come from? Does `entry` mean package name? How does `entry` differ from `worker.entry`?

Sorry if I'm asking a lot of random questions. But I need to understand how it's working to be able to maintain this later.

**Comment by remcohaszing** [comment]
Given the following snippet from the readme:

https://github.com/remcohaszing/monaco-yaml/blob/8378b9aa174aca2e559c9ea53f12626ae7e52433/README.md?plain=1#L94-L95

And the following snippet in the `monaco-editor-webpack-plugin` example:

https://github.com/remcohaszing/monaco-yaml/blob/8378b9aa174aca2e559c9ea53f12626ae7e52433/examples/monaco-editor-webpack-plugin/webpack.config.js#L19-L32

- `customLanguages[0].label`: matches the label of the worker to load. It must match the label `monaco-yaml` passes here:
  https://github.com/remcohaszing/monaco-yaml/blob/8378b9aa174aca2e559c9ea53f12626ae7e52433/src/yamlMode.ts#L55
- `customLanguages[0].entry`: This tells the webpack plugin which file module import to inject.
- `customLanguages[0].worker.entry`: This tells the webpack plugin where to load the worker from.
- `customLanguages[0].worker.id`: I think this is related to UMD support. Whatever it is, it can be safely omitted. I think it’s technically supposed to match the value specified here:
  https://github.com/remcohaszing/monaco-yaml/blob/8378b9aa174aca2e559c9ea53f12626ae7e52433/src/yamlMode.ts#L56
