### ISSUE TITLE
Tries to download schema even though it is provided

### ISSUE THREAD

**Issue by golergka** [remcohaszing/monaco-yaml#175]
In the API documentation about `uri` parameter [it says that](https://github.com/remcohaszing/monaco-yaml/blob/main/index.d.ts#L20-L23):

> JSON schema will be downloaded from here if no schema was supplied

Which lead me to believe that if I provide a schema, the plugin won't try to download it. However, this is not the case for me — even though I provided a schema, it still tries to download it.

Here's my configuration:

```Typescript
  monacoYaml.setDiagnosticsOptions({
    hover: true,
    completion: true,
    format: true,
    validate: true,
    enableSchemaRequest: true,
    schemas: [
      {
        uri: "http://placeholder",
        fileMatch: ["file_name.yml"],
        schema: {
          $schema: "http://json-schema.org/draft-07/schema#",
          $id: "http://placeholder",
          title: "placeholder title",
          description: "placeholder description",
          type: "object",
          properties: {
            name: {
              description: "name property description",
              type: "string",
            },
          },
          required: ["name"],
        },
      },
    ],
  });
```

And here's what I see in my Monaco instance:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/929735/169286023-678bcd82-ec6e-4a31-9cc5-cbf4eb67aef0.png">

The fact that it displays `http://placeholder` url tells me that it correctly associated the model with the filename pattern, but I expected it not to attempt to download a schema because it's already provided.

If I change the `enableSchemaRequest: false`, the error message text changes, but the issue remains:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/929735/169286506-de43ae63-885f-43fa-afb3-3629298aacb0.png">

What is the correct way to only use schemas supplied by the application itself?

**Comment by remcohaszing** [comment]
Closed by #176
