### ISSUE TITLE
Add option to hide schema URI/name in tooltips

### ISSUE THREAD

**Issue by safareli** [remcohaszing/monaco-yaml#177]
It would be great to have an option that would hide all the texts that expose the URI or name of the schema

![Screen Shot 2022-06-08 at 19 10 03](https://user-images.githubusercontent.com/1932383/172652489-b8987412-42c7-4760-8eb4-4a3075439998.png)

turning that off would hide the name of schema in `Source: ....json` as well as in `yaml-schema: http:///.......json`

**Comment by remcohaszing** [comment]
Thanks for your suggestion! I like the idea, but this is handled by `yaml-language-server`. If you can convince them to add an option for it, I’ll gladly support it.

One tip: If you pass a schema as an object and an unrelated uri, the schema will be used, but the given uri will be rendered. For example you could link to your documentation website or SwaggerUI page, whatever works for you :smile:

**Comment by safareli** [comment]
That's sort of what I'm doing, but wanted to just remove it. One thing we can do might be to expose some hook that can be used to alter data retuned by yaml-language-server.

**Comment by domsew** [comment]
Related issue #143 (possible duplicate)

**Comment by safareli** [comment]
Here is PR to fix this https://github.com/remcohaszing/monaco-yaml/pull/180

**Comment by remcohaszing** [comment]
I will implement this option if `yaml-language-server` supports it. Until then, it’s not actionable from `monaco-yaml`.
