### ISSUE TITLE
`monaco.languages.yaml` stopped working

### ISSUE THREAD

**Issue by domsew** [remcohaszing/monaco-yaml#178]
I detected that in the current version the global syntax `monaco.languages.yaml` is `undefined`. I guess it is a regression. I noticed that the problem was partially solved by #172, but probably we should add something like [this](https://github.com/microsoft/monaco-editor/blob/a5298e13bba5ab5d97ccef97c7b56df9cec489ce/src/language/json/monaco.contribution.ts#L201). Note that it would violate coding style rules.

**Comment by domsew** [comment]
Such syntax is recommended by monaco team and can be seen in provided [examples](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults). From `monaco-yaml` (as a monaco-editor plugin / extension) I would expect to have consistent API and to be as close as possible with the base project. It is best to allow users to use YAML language as any other language available in the editor.

**Comment by remcohaszing** [comment]
They use it for the builtin language support, but I don’t see any recommendations to use it for external plugins.

This old behaviour was confusing for no real benefit. It meant people first had to import `monaco-yaml`. This then monkey patched the `monaco-editor` module, which people then had to import in order to actually use `monaco.languages.yaml`. This leads to hard to explain and hard to debug issues for no benefit. Now people can just import what they need from `monaco-yaml` and use the API like any other library.

**Comment by amir2mi** [comment]
The reason for not having this is valid, and I used your solution [mentioned here](https://github.com/remcohaszing/monaco-yaml/issues/98#issuecomment-907815546) to `setDiagnosticsOptions`.
However, this sets the validation for all YAML instances and I need to have it for specific ones.

In my case, I wanted to have custom schema for YAML that validates `key=value` pair. 
That is my schema:
```js
setDiagnosticsOptions({
  enableSchemaRequest: true,
  hover: true,
  completion: true,
  validate: true,
  format: true,
  schemas: [
    {
      uri: "http://validation/yaml-key-value-schema.json",
      fileMatch: ["*"],
      schema: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["key", "value"],
          properties: {
            key: {
              type: ["string", "number"],
            },
            value: {
              type: ["string", "number"],
            },
          },
        },
      },
    },
  ],
});
```

I have no idea how to activate it for specific instances where I need `key=pair` value, if I had access to the `monaco.languages.yaml.yamlDefaults.setLanguageConfiguration` I could set validation per instance.

**Comment by remcohaszing** [comment]
Sorry, I don’t understand what you’re trying to do. Could you open a new issue and explain what you mean by _instance_? Your examples shows `fileMatch: ['*']`, which applies to all models.
