### ISSUE TITLE
Enum autocomplete is not working when inside double/single quotes

### ISSUE THREAD

**Issue by skymansandy** [remcohaszing/monaco-yaml#181]
It works when I press ctrl+space after colon directly.
<img width="577" alt="Screenshot 2022-07-01 at 12 01 58 AM" src="https://user-images.githubusercontent.com/17377683/176752376-b69618c9-d61b-418d-9966-f54bdba0e24a.png">

But when I do the same inside quotes, It says 'No Suggestions'.
<img width="591" alt="Screenshot 2022-07-01 at 12 02 04 AM" src="https://user-images.githubusercontent.com/17377683/176752425-c19f4b37-7fbc-475d-a41c-b18b054d7a65.png">

Can someone pls help?

**Comment by remcohaszing** [comment]
I managed to reproduce this issue in VSCode as well. This means it’s a bug in [`yaml-language-server`](https://github.com/redhat-developer/yaml-language-server). Please report the issue upstream.
