### ISSUE TITLE
Any Future Plan to support @monaco-editor/loader

### ISSUE THREAD

**Issue by viranmalaka** [remcohaszing/monaco-yaml#183]
Hi team, 
Your Readme clearly state that this library is not working with `@monaco-editor/loader` or `@monaco-editor/react` in the FAQ section.

But I just need to ask that, do you have any feature plan to improve `monaco-yaml` to work with above two?. 

My real problem is, I was working on a next-js project with monaco editor and I created the editor by using above mentioned `@monaco-editor/loader` library. Now I got a requirement to support YAML editing feature and I'm block due to this reason. 

Appreciate it if someone can point me out a working example in next-js which use YAML in monaco editor.

**Comment by remcohaszing** [comment]
I happen to be working with Monaco editor inside a Next.js project right now.

First, here’s a solution to working with `monaco-editor` without having to use `@monaco-editor/react`:

**next.config.js**

```js
export default {
  webpack(config, options) {
    // https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3
    if (!options.isServer) {
      const specificRules = config.module.rules.find((rule) => rule.oneOf).oneOf
      const cssRule = specificRules.find(
        (rule) =>
          rule.test &&
          Array.isArray(rule.use) &&
          [].concat(rule.test).some((test) => test.test('anything.css'))
      )
      specificRules.unshift({
        sideEffects: true,
        test: /[\\/]node_modules[\\/]monaco-editor[\\/].+\.css$/,
        use: cssRule.use,
      })
    }
  }
}
```

**components/MonacoEditor/index.ts**

```ts
import dynamic from 'next/dynamic'

export const MonacoEditor = dynamic(() => import('./MonacoEditor'), { ssr: false })
```

**components/MonacoEditor/MonacoEditor.tsx**

```ts
import * as monaco from 'monaco-editor'
import { setDiagnosticsOptions } from 'monaco-yaml';

export default function MonacoEditor() {
  return (
    <div
      ref={(node) => {
        const editor = monaco.editor.create(node, options)
      }}
    />
  )
}
```

Just make sure everything related to Monaco is handled by this `next/dynamic` import.

---

As for support for `@monaco-react/loader`:I currently don’t have plans to actively work on it, but I am open to a pull request. I have recently created [`monaco-tailwindcss`](https://github.com/remcohaszing/monaco-tailwindcss) and [`monaco-unified`](https://github.com/remcohaszing/monaco-unified) which support passing in the `monaco-editor` module when configuring. `monaco-yaml` could work the same way.

**Comment by vmal3951** [comment]
@remcohaszing I highly appreciate your quick response and the support. My requirement is working now. 

Note: for those who are referring to this in future, you will have to return the webpack config in `next.config.js` file.

```javascript
export default {
  webpack(config, options) {
    // https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3
    if (!options.isServer) {
      const specificRules = config.module.rules.find((rule) => rule.oneOf).oneOf
      const cssRule = specificRules.find(
        (rule) =>
          rule.test &&
          Array.isArray(rule.use) &&
          [].concat(rule.test).some((test) => test.test('anything.css'))
      )
      specificRules.unshift({
        sideEffects: true,
        test: /[\\/]node_modules[\\/]monaco-editor[\\/].+\.css$/,
        use: cssRule.use,
      })
    }
    return config;
  }
}
```
