### ISSUE TITLE
Suggestion: How to show Schema validation errors like attached in an image 

### ISSUE THREAD

**Issue by alpesh1988** [remcohaszing/monaco-yaml#187]
![image](https://user-images.githubusercontent.com/4091706/188482550-0035db58-13b5-42f1-a313-f263bb2f9633.png)

Hello, The question is simple. Hope to receive reply :)

**Comment by remcohaszing** [comment]
That’s done by these lines:

https://github.com/remcohaszing/monaco-yaml/blob/831aa841607fbd74e16e1cffd16f96dabf4ec792/examples/demo/src/index.ts#L214-L242
