### ISSUE TITLE
Autocomplete for properties possible?

### ISSUE THREAD

**Issue by aeneaswiener** [remcohaszing/monaco-yaml#191]
Hi,  is there any way at all we can achieve an autocomplete experience for the properties declared in a JSON schema? So that when the user is inside an object and they are not sure what all the available properties are that they could set, they can just start typing and get suggestions, like shown in the mock up below? 

<img width="887" alt="image" src="https://user-images.githubusercontent.com/4281507/194762082-126b6144-1194-440e-860e-22b1df2b3d57.png">

**Comment by aeneaswiener** [comment]
Turns out it already works with pressing control / command + space to show the suggestions

If you want them to show up automatically here is the way how https://stackoverflow.com/questions/55560539/autosuggest-for-json-files-with-custom-schema-for-monaco-editor

**Comment by mazhe-nerd** [comment]
> Turns out it already works with pressing control / command + space to show the suggestions
> 
> If you want them to show up automatically here is the way how https://stackoverflow.com/questions/55560539/autosuggest-for-json-files-with-custom-schema-for-monaco-editor

Excuse me，how to add code to this example：https://github.com/remcohaszing/monaco-yaml/blob/main/examples/demo/src/index.ts
