### ISSUE TITLE
Support deprecated decorator for json schema 

### ISSUE THREAD

**Issue by Resetand** [remcohaszing/monaco-yaml#192]
The case is pretty simple, seems like json schema supports a "deprecated" arrtibute – http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3

```
"type": "object",
  "properties": {
    "property": {
      "description": "I have a description"
    },
    "deprecatedProperty": {
      "deprecated": true
      "description": "This property is deprecated, please use a 'property' field"
    },
```

In this case i want to strike-through this property, like

<img width="182" alt="Screenshot 2022-10-30 at 13 38 17" src="https://user-images.githubusercontent.com/33288402/198867681-d3526be6-03ef-4f03-957b-9b32d21d5a68.png">

**Comment by Resetand** [comment]
As far as i know, monaco editor supports a `Deprecated` tag for markers

<img width="300" alt="Screenshot 2022-10-30 at 13 41 47" src="https://user-images.githubusercontent.com/33288402/198867790-bb6ef837-b1b3-4cfd-92eb-29999a26ccf9.png">

**Comment by remcohaszing** [comment]
I would like this too, but it needs to be fixed upstream in `json-languageservice`. See https://github.com/microsoft/vscode-json-languageservice/issues/87.

I'm closing this as it's not actionable from this repository.

**Comment by florentchauveau** [comment]
Hello there! It has been fixed upstream https://github.com/microsoft/vscode-json-languageservice/issues/87 by https://github.com/microsoft/vscode-json-languageservice/pull/133. May we re-open this? 🙏

**Comment by remcohaszing** [comment]
I'm glad this is fixed upstream, but there's no need to re-open this. It will be fixed once `yaml-language-server` updates `vscode-json-languageservice` so `monaco-yaml` can update.
