### ISSUE TITLE
"workspaces" key is being shipped in the released npm module package.json

### ISSUE THREAD

**Issue by mistic** [remcohaszing/monaco-yaml#197]
Currently the `package.json` being shipped with the node_module contains a `workspaces` key that is a development artifact only. 

This is causing `yarn` to display a warning during install `warning Workspaces can only be enabled in private projects.` and should be removed.

**Comment by remcohaszing** [comment]
This is a bug in yarn, not this package.

**Comment by mistic** [comment]
@remcohaszing why do you think it is a bug in yarn? There is a long discussion happening at https://github.com/yarnpkg/yarn/issues/8580 about this and no conclusion was made. It looks like yarn is on purpose emitting this warning as the workspaces key is intended for develop only environments or private repositories. 

Can't we just extend the release pipeline to quickly change the `package.json` removing this `workspaces` key?
