### ISSUE TITLE
null links in createLinkProvider

### ISSUE THREAD

**Issue by duggiemitchell** [remcohaszing/monaco-yaml#198]
👋🏾 We are using monaco-yaml to provide yaml language support for monaco editor. Prior to the `4.0.3` release, we were getting the following [error related to telemetry:](https://github.com/remcohaszing/monaco-yaml/issues/190) 
```
Cannot read properties of null (reading 'sendError')

TypeError: Cannot read properties of null (reading 'sendError')
at Object.findLinks
```
Which may have been masking another error; after upgrading, this is the new error:

```
Cannot read properties of undefined (reading 'map')

TypeError: Cannot read properties of undefined (reading 'map')
at Object.provideLinks
```
For context, this is a React application without the use of a remote schema, and using default diagnostic options. Also, this seems to just affect new users; I haven't been able to reproduce this locally - and  its mostly caught by our frontend monitoring and e2e tests. 

I appreciate your help.

**Comment by remcohaszing** [comment]
Thanks! I was expecting the telemetry error fix to uncover other, more real errors.

Could you provide more information? Specifically:

- A full stack trace
- Instructions how to reproduce the issue. I understand you are having problems reproducing it, but I really need to be able to reproduce it myself in order to fix it. Maybe you should clear your cache or use guest mode?
- Also browser information could be helpful

**Comment by duggiemitchell** [comment]
1. A full stack trace

```
Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.provideLinks (webpack-internal:///<NUMBER>:343:22)
```

2. Instructions how to reproduce the issue. I understand you are having problems reproducing it, but I really need to be able to reproduce it myself in order to fix it. Maybe you should clear your cache or use guest mode?

This is tricky as I've been able to repro only in e2e tests, but can say it throws the error before anything is rendered to the browser - according to cypress recordings.  We are initializing the dignostics and editor in a useEffect:

```
const model = Uri.parse(fileName);
....

  React.useEffect(() => {
    if (editorRef?.current) {
      setDiagnosticsOptions();
      const ed = editor.create(
        editorRef.current,
        {
          ...options,
          model: editor.createModel(value, 'yaml', model),
        },
        {}
      );
      setXed(ed);
    }
    return () => editor.getModels().forEach(model => model.dispose());
  }, []);
```

3. Also browser information could be helpful
This is happening mostly on Chrome, though that could just be what most of us use.

Additional helpful things:
- we are not using a schema
- for the build, we're using webpack + monaco webpack plugin

**Comment by remcohaszing** [comment]
I don’t have full context, nor do I think it’s related to the issue, but I think you should dispose the editor in the React `useEffect` cleanup.

```diff
  const model = Uri.parse(fileName);
  // …

  React.useEffect(() => {
    if (editorRef?.current) {
      setDiagnosticsOptions();
      const ed = editor.create(
        editorRef.current,
        {
          ...options,
          model: editor.createModel(value, 'yaml', model),
        },
        {}
      );
      setXed(ed);
    }
-   return () => editor.getModels().forEach(model => model.dispose());
+   return () => {
+     ed.dispose();
+     editor.getModels().forEach(model => model.dispose());
+   };
  }, []);
```
