### ISSUE TITLE
Support for 2019 json schema validation

### ISSUE THREAD

**Issue by mitodrummer** [remcohaszing/monaco-yaml#200]
Are there plans to update from draft-7?

**Comment by remcohaszing** [comment]
`monaco-yaml` supports whatever `yaml-language-server` supports. And they depend on `json-languageservice`. You'll need to ask them.

Once they support it, I'll update `monaco-yaml`.

**Comment by mitodrummer** [comment]
Thanks! I've opened an issue here https://github.com/redhat-developer/yaml-language-server/issues/856
