### ISSUE TITLE
how can i use monaco-yaml with @monaco-editor/react

### ISSUE THREAD

**Issue by lakshay927** [remcohaszing/monaco-yaml#204]
i have an existing project where i am using  @monaco-editor/react and i want to have yaml validations on a click of a button. what should be the best possible way to do it?

**Comment by lakshay927** [comment]
what if i use monaco editor and the real-time validation can you just give me a link with a relevant code for this?

**Comment by remcohaszing** [comment]
I don’t understand. Why don’t you want real-time validation? What are you really trying to do?

**Comment by lakshay927** [comment]
I am sorry i think there is some misunderstanding. I got your point and i just want the simple real-time  validation as you suggested working with monaco editor. I hope you understand.

Thanks!!

**Comment by remcohaszing** [comment]
Ah right. I think the simplest example is https://github.com/remcohaszing/monaco-yaml/blob/main/examples/vite-example/index.js

**Comment by lakshay927** [comment]
Thank you for your prompt responses! I appreciate it. I also sent you a direct message on Twitter, so when you have a chance, could you kindly check it out? Thank you in advance for your time and assistance.
