### ISSUE TITLE
Autocomplete does not work when root level of schema is of type "array"

### ISSUE THREAD

**Issue by HansDP** [remcohaszing/monaco-yaml#205]
I have an issue when I use an array on the root of the schema.

When editing yaml using such a schema, the first entry in the list works as expected.
The second item in the list only has auto-complete options for properties that have not been consumed in the first item.

To reproduce this issue:

1) open the Monaco YAML playground (https://monaco-yaml.js.org/)
2) select the option ".pre-commit-hooks.yml" sample
3) clear the content of the editor
4) start typing:
```
- name: my name 1
  id: my id 1
  language: system
  entry: my entry 1
```
The auto complete feature for this works perfectly
<img width="642" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/918330/06dc6f72-ea94-402a-a1f1-5510af43516b">

5) add a new entry in the list, and open the auto-complete list
<img width="642" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/918330/6ffb4390-6067-40bc-bebe-942dfc966102">

For the first property, all auto-complete options are available, as shown in the screenshot

When I specify e.g. a name:
```
- name: other name
```

When now adding a new property to the second item in the list, the options `id`, `language` and `entry` are not available in the auto-complete list (using ctrl-space to get the list op autocomplete options). These are the options specified in the first item in the list.
<img width="642" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/918330/ca658920-0edf-48cb-bf40-bf01fbff12de">

*Note that validating the YAML file is still correct.*

When removing one of the properties in the first item in the list (eg. `id`), that property now becomes available in the auto-complete options of the second item:
<img width="642" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/918330/d6eff43c-d5a3-48cb-bc32-91f1830432f9">

It would help me a great deal if this issue could be resolved.

**Comment by remcohaszing** [comment]
This is definitely a bug! However, I reproduced this in YAML for VSCode as well. Please report an upstream issue to [`yaml-language-server`](https://github.com/redhat-developer/yaml-language-server) instead.
