### ISSUE TITLE
Bad properties suggested in autocomplete

### ISSUE THREAD

**Issue by Skraye** [remcohaszing/monaco-yaml#207]
Hello, 

When upgrading to monaco-yaml 4.0.4, coming from 4.0.0-alpha.0, we face an issue where autocomplete suggests all properties of existing objects.

Here is an example for more clarity : 
![image](https://github.com/remcohaszing/monaco-yaml/assets/37600690/13b783f3-2d85-4315-be5a-c47cad305364)

As you can see, in our list of tasks, each one has properties depending on their type.
The `io.kestra.core.tasks.debugs.Return` or  `Return` does not have `destinationTable`, as you can imagine, but `Bigquery.Query` does! 

To help you reproduce it, I've forked the monaco-yaml library and replace the JSON schema by ours in the demo workspace: https://github.com/Skraye/monaco-yaml

Ping me if you need more information, thanks.

**Comment by remcohaszing** [comment]
Can this be reproduced in `yaml-language-server` / YAML for VSCode? If so, it’s an upstream bug in `yaml-language-server`.

**Comment by Skraye** [comment]
Face the issue in VSCode with the YAML extension. I guess your supposition is right!

**Comment by remcohaszing** [comment]
This is an issue in `yaml-language-server` then, not `monaco-yaml`.
