### ISSUE TITLE
Link to Angular example in readme is not working

### ISSUE THREAD

**Issue by Celtian** [remcohaszing/monaco-yaml#208]
You have link in readme...

https://github.com/microsoft/monaco-editor/tree/main/monaco-editor-samples

![image](https://github.com/remcohaszing/monaco-yaml/assets/18282249/4f6e595a-0409-4196-a247-3c8a204fe680)

But there is nothing.

Thx...

**Comment by remcohaszing** [comment]
Apparently they moved it to https://github.com/microsoft/monaco-editor/tree/main/samples. Would you like to update it in a PR?

**Comment by remcohaszing** [comment]
This was fixed by #210
