### ISSUE TITLE
Hover not showing examples as yaml but json

### ISSUE THREAD

**Issue by q-rault** [remcohaszing/monaco-yaml#209]
Hello everyone,
First, thanks for your work on this project! 🙂

As you may know, `"examples"` is a reserved keyword (not for json-schema, but at least monaco-editor),
that we may use to display examples to the user when hovering a property.

I faced an bug where my examples would be shown as JSON to the end user (which is not very practical if they're not very used to this syntax, yaml would be better, as we're already using this syntax in the editor).

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/monaco-yaml/yaml.worker.js b/node_modules/monaco-yaml/yaml.worker.js
index 91aacd0..08d9857 100644
--- a/node_modules/monaco-yaml/yaml.worker.js
+++ b/node_modules/monaco-yaml/yaml.worker.js
@@ -6700,6 +6700,7 @@ function setKubernetesParserOption(jsonDocuments, option) {
 
 // node_modules/yaml-language-server/lib/esm/languageservice/services/yamlHover.js
 import { URI as URI5 } from "vscode-uri";
+import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
 import * as path3 from "path-browserify";
 var YAMLHover = class {
   constructor(schemaService, telemetry2) {
@@ -6831,12 +6832,15 @@ var YAMLHover = class {
           if (result.length > 0) {
             result += "\n\n";
           }
-          result += "Examples:";
-          markdownExamples.forEach((example) => {
-            result += `
-
-\`\`\`${example}\`\`\``;
+          result += "Examples:  \n";
+          const parsedYamlExamples = markdownExamples.map((example) => {
+            return `
+\`\`\`
+${stringifyYaml(parseYaml(example))}
+\`\`\`
+`;
           });
+          result += parsedYamlExamples.join(`or`);
         }
         if (result.length > 0 && schema.schema.url) {
           result += `
```

Result:

![changes](https://github.com/remcohaszing/monaco-yaml/assets/94388164/94f35d6f-647c-4b86-a943-d1bf48be09c7)
![changes_array](https://github.com/remcohaszing/monaco-yaml/assets/94388164/32b60c5d-e5e0-4b42-ada5-a8569aea7d6e)

If I understand from a different issue but relying on the same part of the code (https://github.com/remcohaszing/monaco-yaml/issues/177),
it will be better to change it directly on yaml-language-server (though I believe it's interesting to mention it here at least as it might be an monaco-related issue.

Hope this helps someone

**Comment by remcohaszing** [comment]
This sounds great! I didn’t even know examples are supported. Technically JSON is valid YAML, but I get what you mean.

This is an upstream issue in [`yaml-language-server`](https://github.com/redhat-developer/yaml-language-server) though. Please open an issue there. I look forward to pulling those changes into `monaco-yaml`. :)

Additionally I think it would be nice if those code blocks get YAML syntax highlighting.
