### ISSUE TITLE
How to get the values of a aymbol which is an array type?

### ISSUE THREAD

**Issue by venkat-raman-wday** [remcohaszing/monaco-yaml#215]
Hello this is a question,

I'm trying to get the values of a symbol which is of type array. From the demo example, it looks like the value of a string type is exposed in the `detail` property and the `iterateSymbols` is able to iterate over the document's symbols given the position.

I'd like to know how to get the values of a symbol which is of array type. Any pointers will be very helpful. Thanks.

**Comment by remcohaszing** [comment]
Could you elaborate what you’re trying to do? If you want to parse YAML, use the [yaml](https://eemeli.org/yaml) package.

I’m closing this as it seems off-topic, but feel free to ask questions.

**Comment by venkat-raman-wday** [comment]
Please ignore it. I was just looking for a way to get the values corresponding to a symbol if it's of type array. I found how to do it. Thanks!
