### ISSUE TITLE
Can I use setDiagnosticsOptions for multiple schemas that are fetched lazily?

### ISSUE THREAD

**Issue by rameshx** [remcohaszing/monaco-yaml#216]
I am using `react-monaco-editor` to render multiple `MonacoEditor` components in an app, and each component calls an API to fetch the schema it needs. For one component in a page, I'm calling `setDiagnosticsOptions` like below, and it works. 

```typescript
<MonacoEditor
    editorWillMount={() => {
      setDiagnosticsOptions({
        validate: true,
        enableSchemaRequest: false,
        hover: true,
        completion: true,
        schemas: [
          {
            schema: fetchedSchema,
            // using * as I'm not sure what is the correct value for fileMatch
            fileMatch: ['*'],
            // using a fake URI as the API only returns a schema object and does not return a URI of that schema
            uri: 'https://github.com/foo.json'
          }
        ]
      })
  }}
/>
```
How can I call `setDiagnosticsOptions` when rendering multiple editor components on the same page? The schemas that the other components need are fetched later as these components are rendered conditionally based on user events.

If I call `setDiagnosticsOptions` with a different schema in another component, I think it will replace the previous schema. Can `fileMatch` and `uri` be used to solve this? I also noticed that in the latest version of `react-monaco-editor`, `MonacoEditor` also takes a `uri` prop that is used when creating a model (`monaco.editor.createModel(finalValue, language, modelUri)`). If I store all the schemas in one place and call `setDiagnosticsOptions` by passing all schemas every time a schema is fetched, that would solve the overwrite problem, but how can I link a schema to a component?

**Comment by remcohaszing** [comment]
This looks a lot like #214.

You should also read https://github.com/microsoft/monaco-editor#concepts
