### ISSUE TITLE
Autocomplete initializes the value with null instead of it's optional values

### ISSUE THREAD

**Issue by mleitenbauer** [remcohaszing/monaco-yaml#217]
Is it possible to change the autocomplete behavior so it initializes my modules with it's optional values.

In VS - Code it's working as expected.

Current Behavior:
![current-behaviour](https://github.com/remcohaszing/monaco-yaml/assets/69802329/ba6000f8-8b68-4182-b176-5c52cb81ec09)

Expected Behavior:
![expected-behaviour](https://github.com/remcohaszing/monaco-yaml/assets/69802329/e02d64d7-d52b-4ead-87d1-236cf9c8f870)

Do I have to adjust the schema ? Or is there any flag in DiagnosticOptions I can use ? 

Thanks in advance

**Comment by remcohaszing** [comment]
Can you check if this works on https://monaco-yaml.js.org? If not, please share a link to the JSON schema.

**Comment by mleitenbauer** [comment]
So I started the webpack demo version, you provided in example/demo.
I'm still facing the same issue.

Here is a broken down schema I'm using.

`{
  "schemaType": "Test Schema",
  "name": "Test Scripts",
  "description": "Intellisense Test Scripts",
  "schema": {
    "$defs": {
      "Datasource": {
        "description": "test",
        "properties": {
          "uuid": {
            "description": "UUID for the datasource in database",
            "example": "00000000-0000-0000-0000-000000000006",
            "format": "uuid",
            "title": "Uuid",
            "type": "string"
          },
          "timespan": {
            "anyOf": [{ "$ref": "#/$defs/Timespan" }, { "type": "null" }],
            "default": null
          }
        },
        "required": ["uuid"],
        "title": "Datasource",
        "type": "object"
      },
      "TestModuleBaseclass": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "description": "ID or name for this Rept Module in the structure",
            "title": "Id",
            "type": "string"
          },
          "some_extra_info": {
            "description": "This is some totally necessary info for processing",
            "title": "Some Extra Info",
            "type": "string"
          },
          "order": {
            "description": "order was unexpected, but necessary for this",
            "title": "Order",
            "type": "number"
          },
          "data": { "$ref": "#/$defs/TestModuleDatasources" }
        },
        "required": ["id", "some_extra_info", "order", "data"],
        "title": "TestModuleBaseclass",
        "type": "object"
      },
      "TestModuleDatasources": {
        "additionalProperties": false,
        "description": "",
        "properties": {
          "float_sources": {
            "items": { "$ref": "#/$defs/Datasource" },
            "title": "test Sources",
            "type": "array"
          },
          "indi_sources": {
            "items": { "$ref": "#/$defs/Datasource" },
            "title": "Indi Sources",
            "type": "array"
          },
          "indicator3": { "$ref": "#/$defs/Datasource" }
        },
        "required": ["float_sources", "indi_sources", "indicator3"],
        "title": "TestModuleDatasources",
        "type": "object"
      },
      "TestModuleMainclass": {
        "additionalProperties": false,
        "properties": {
          "TestModule": {
            "anyOf": [{ "$ref": "#/$defs/TestModuleBaseclass" }, { "type": "null" }],
            "default": null
          }
        },
        "title": "TestModuleMainclass",
        "type": "object"
      },
      "Timespan": {
        "description": "Timespan Test",
        "properties": {
          "unit": {
            "description": "Unit of the timespan -> day, week, month, starting from the last full calendarial interval",
            "enum": ["day", "week", "month", "year"],
            "title": "Unit",
            "type": "string"
          },
          "count": {
            "description": "number of days, weeks, months, years",
            "title": "Count",
            "type": "integer"
          },
          "requestmode": {
            "description": "how the request to the DB should be handled, e.g. all data, 5min Avg, ... ",
            "enum": ["all", "timebucket 5 min", "timebucket 1 hour", "timebucket 1 day"],
            "title": "Requestmode",
            "type": "string"
          },
          "startmode": {
            "description": "Defines the relative startpoint of the time - end for the last x units, begin for the first x units",
            "enum": ["begin", "end"],
            "title": "Startmode",
            "type": "string"
          }
        },
        "required": ["unit", "count", "requestmode", "startmode"],
        "title": "Timespan",
        "type": "object"
      },
      "ValueClass": {
        "enum": [
          "v_peak_f"
        ],
        "title": "ValueClass",
        "type": "string"
      }
    },
    "additionalProperties": false,
    "properties": {
      "module": {
        "anyOf": [
          { "$ref": "#/$defs/TestModuleMainclass" }
        ],
        "description": "The module that should be executed with its configured input data",
        "title": "Module"
      }
    },
    "required": ["module"],
    "title": "YamlSchema",
    "type": "object"
  }
}
`

**Comment by remcohaszing** [comment]
The schema you provided only defined `#/module/TestModule`, not `#/module/NodeModule` like in the original issue. This property is indeed autocompleted as null, but so is it using the YAML extension VSCode. The default value for the subschema is `null`. Changing the default value for that subschema also changes the value autocomplete resolves to.

Everything looks to be working as expected.
