### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by zachterrell57** [remcohaszing/monaco-yaml#219]
When trying to use `monaco-yaml` in a NextJS project I am met with this error:
<img width="979" alt="CleanShot 2023-09-05 at 14 39 04@2x" src="https://github.com/remcohaszing/monaco-yaml/assets/49534342/7304b9e8-bf51-4b38-addd-3d634ff35ab3">

I saw in another thread that this library will work with NextJS, so is there a solution to this problem? Thanks!

**Comment by remcohaszing** [comment]
It is possible to use `monaco-editor` in a Next.js project. I personally got this to work. However, this was in a proprietary code base I no longer have access to, so I can’t just give you a step-by-step guide how to do it.

It involves using [`next/dynamic`](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic) to make sure `monaco-editor` is only imported in client-side code, not server side.

Also you also need to patch the [Next.js webpack config](https://nextjs.org/docs/app/api-reference/next-config-js/webpack). Specifically, you need to patch the rule for loading CSS files. If I recall correctly, you should only do so if `isServer` is false.

I can’t think of any technical reasons Next.js doesn’t allow third party packages to import CSS. It’s an artificial limitation by Next.js. I suggest searching the Next.js issue tracker for similar issues or creating a new one to suggest to allow this.

This question is related to using `monaco-editor` in Next.js. It’s not about `monaco-yaml`, so I’m closing this issue.

**Comment by roshan-gh** [comment]
@zachterrell57 if you want to use monaco-yaml features in monaco editor and nextJS, here this is my approach:
1- install [@monaco-editor-react](https://github.com/suren-atoyan/monaco-react)
2- install monaco-yaml
3- with window.MonacoEnvironment import monaco-yaml worker to your monaco-editor-react

if you get stuck in any step, I can give you the details.

**Comment by zachterrell57** [comment]
hey @roshan-gh, thanks for the tips!

I currently have monaco-react working, and only got this CSS error once I installed monaco-yaml and tried to run it as outlined in the repo. I'll try you approach with 3. and get back to you, thanks!

**Comment by remcohaszing** [comment]
Note that `@monaco-editor/react` works, because it downloads Monaco from a CDN. It also abstracts away various [concepts](https://github.com/microsoft/monaco-editor#concepts). It may work for you, but I personally recommend against it.

It is possible to make the `monaco-editor` package work with Next.js.

**Comment by kachkaev** [comment]
👋 folks! Next.js and `@monaco-editor/react` user here. If anyone has managed to get `monaco-editor` and `monaco-yaml` working with Next.js, could you please share a sandbox? I am bumping into issues mentioned above and can't get all three things working together. I might be missing something trivial, but it'd be great if someone could share a shortcut. It seems like it is necessary to switch away from `@monaco-editor/react` (because of a CDN) and doing that needs some low-level bundler / worker knowledge.

**Comment by remcohaszing** [comment]
The client for whom I integrated `monaco-editor` in Next.js at the time was so nice to share their `next.config.js` with me :heart: 

I trimmed it down a bit. I think this should do the trick:

```js
'use strict'

/**
 * @import {NextConfig} from 'next'
 */

/**
 * @type {NextConfig}
 */
const nextConfig = {
  webpack(config, { isServer }) {
    // https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3
    if (!isServer) {
      const specificRules = config.module?.rules.find((rule) => rule.oneOf).oneOf

      const cssRule = specificRules.find((rule) => {
        if (!rule.test) {
          return false
        }

        if (Array.isArray(rule.test)) {
          return (
            [rule.test].flat().some((test) => test.test('anything.css')) &&
            rule.use.loader !== 'error-loader'
          )
        }

        if (typeof rule.test.test === 'function') {
          return rule.test.test('anything.css') && rule.use.loader !== 'error-loader'
        }
      })

      specificRules.unshift({
        sideEffects: true,
        test: /[/\\]node_modules[/\\]monaco-editor[/\\].+\.css$/,
        use: cssRule?.use
      })
    }

    return config
  }
}

module.exports = nextConfig
```

IIRC this was for Next.js 12 or 13. It may need some tweaking. I would love to hear if this works, or what tweaks are needed.
