### ISSUE TITLE
How to test the demos with a locally-modified version of `yaml-language-server`?

### ISSUE THREAD

**Issue by GavinRay97** [remcohaszing/monaco-yaml#220]
Hiya, thanks so much for porting the YAML LSP to Monaco.

I'm trying to test a modified version of the `yaml-language-server` in Monaco, and to do this I've replaced the `package.json` dependency with the local path to the server:

```json5
{
  "devDependencies": {
	// ...
    "yaml-language-server": "file:../server"
  }
}
```

When I run `npm start` however, I get the following error:
```ps1
ERROR in ./src/index.ts 34:22-44
Module not found: Error: Cant resolve 'monaco-yaml' in '/projects/lsp-server/monaco-yaml/examples/demo/src'

ERROR in ./src/index.ts 43:23-86
Module not found: Error: Cant resolve 'monaco-yaml/yaml.worker' in '/projects/lsp-server/monaco-yaml/examples/demo/src'
```

I hope I'm not missing something obvious -- thank you!

**EDIT:** This same issue happens if I `git clone ... / npm ci / npm start` with a fresh repo, so I think I mistakenly assumed it was due to the YAML LSP change.

**Comment by GavinRay97** [comment]
Update: I'm an idiot and I forgot to run `npm run prepack` to generate the `index.js` that `main` points to 🤦 

However, I get this last error. If I close the webpack error `<iframe>` everything seems to work though:
```
Uncaught runtime errors:

ERROR
Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/1f77b3f3063828b7e99d.js' failed to load.
    at handleError (http://localhost:8081/23a9d3fb6af22cc41653.js:193676:58)
    at http://localhost:8081/23a9d3fb6af22cc41653.js:193695:7

ERROR
Unexpected usage
    at EditorSimpleWorker.loadForeignModule (http://localhost:8081/23a9d3fb6af22cc41653.js:106441:31)
    at http://localhost:8081/23a9d3fb6af22cc41653.js:56713:30
    at async Object.provideMarkerData (http://localhost:8081/23a9d3fb6af22cc41653.js:194831:22)
    at async doValidate (http://localhost:8081/23a9d3fb6af22cc41653.js:198070:25)
```

**Comment by remcohaszing** [comment]
You're not an idiot! You're awesome for wanting to contribute! I'm curious to know see what contribution you'll bring 🙂

I think the error is a caching issue. It's annoying, but you can work around it.
