### ISSUE TITLE
how to use `yaml` as an embedded language

### ISSUE THREAD

**Issue by Yokozuna59** [remcohaszing/monaco-yaml#222]
Hi there, 

Is there a guide (or is it even possible) to integrate the package into an embedded language in `monaco-editor`? We want to support frontmatter in the document, so when the user types `---`, it should enter `yaml` language:

```yaml
--- # enter yaml
# yaml based code follows schema
--- # exit yaml
regular language code
```

Is it possible to just use `nextEmbeded` in `monarch`? Something like this:

```ts
root: [
  [/---/,   { next: '@yaml_block', nextEmbedded: 'yaml' }],
  ...
]
```

**Comment by remcohaszing** [comment]
No. This isn’t supported by `monaco-yaml`. 

You can possibly make this work with [`@volar/monaco`](https://github.com/volarjs/volar.js/tree/master/packages/monaco) and [`volar-service-yaml`](https://github.com/volarjs/services/tree/master/packages/yaml).

**Comment by Yokozuna59** [comment]
@remcohaszing I see, thanks.

Is there an example I could reference?

**Comment by remcohaszing** [comment]
You will need to create a Volar language module to support whatever language it is you’re trying to support. You can have a look at the (not-yet-released) [MDX language module](https://github.com/mdx-js/mdx-analyzer/blob/5cb6e820f60808bd12fa314cf5b976911eecfb9b/packages/language-service/lib/language-module.js) and [Monaco integration](https://github.com/mdx-js/mdx-analyzer/blob/5cb6e820f60808bd12fa314cf5b976911eecfb9b/packages/monaco/mdx.worker.js). Your use case is probably simpler if you just want to extract frontmatter.

**Comment by Yokozuna59** [comment]
I see.

> Your use case is probably simpler if you just want to extract frontmatter.

We already have a separate process to extract frontmatter; we just want syntax highlighting and schema validation if possible.
