### ISSUE TITLE
Autompletion not working in Example

### ISSUE THREAD

**Issue by JakobDev** [remcohaszing/monaco-yaml#223]
I tried the monaco-editor-webpack-plugin example. First I needed to disable CORS to make it work. I selected the prettierc file. If I hover over the keys, it correctly shows me the description, so the schema is loading, but when I start typing a new key, nothing happens.

**Comment by remcohaszing** [comment]
Could you send a PR to fix CORS issue in the `monaco-editor-webpack-plugin` example?

For the other issue I require more information. What content did you have? Where did you type what character? Does it behave different from the VSCode YAML extension?

**Comment by JakobDev** [comment]
I just tried to type some prettier keys e.g.  `trailingComma` but no popup appears. In VSCode it works without problems. Tested in Firefox and Chrome.
