### ISSUE TITLE
support prettier v3

### ISSUE THREAD

**Issue by artola** [remcohaszing/monaco-yaml#224]
It should be possible to upgrade to Prettier v3 or support both: `prettier: "^2.0.0 | ^3.0.0"`

May be the only thing to care about is the change of the apis to `async`

```ts
// v2
export function format(source: string, options?: Options): string;
```

```ts
// v3
export function format(source: string, options?: Options): Promise<string>;
```

It seems that some used packages/services expect `format` to be sync.

**Comment by remcohaszing** [comment]
Prettier is integrated via `yaml-language-server`. There’s already a PR to update Prettier (https://github.com/redhat-developer/yaml-language-server/pull/909). If that’s merged and released, `monaco-yaml` can update too.

**Comment by remcohaszing** [comment]
I’m closing this, as it’s currently not actionable. It really depends on the upstream issue being resolved and released.
