### ISSUE TITLE
Ability to tweak autocompletion

### ISSUE THREAD

**Issue by bripkens** [remcohaszing/monaco-yaml#228]
Hey folks,

thank you for providing monaco-yaml. It is really helpful!

While using it, we have found that some of the auto-completions aren't working as desired. More specifically, the auto-completion generates fields containing default values (so optional fields and hence noise).

<img width="693" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/596443/01135656-8b27-4389-83c9-e4ee9fb86ea8">

The above is showing a screenshot where `googlecloud` was auto-completed (on [OTelBin](https://www.otelbin.io/s/889928bd-cbf7-42b4-9806-ce1bb96bf1fc)).

From a quick check of the source code, I couldn't see any way to configure this behavior. For example, only to auto-complete required fields without default values.

Is something like this possible?

Thanks

**Comment by remcohaszing** [comment]
I’m glad you like it. :smile: 

The behaviour you’re describing comes from [`yaml-language-server`](https://github.com/redhat-developer/yaml-language-server). `monaco-yaml` has no control over this.
