### ISSUE TITLE
Enum autocomplete didn't put string inside quote

### ISSUE THREAD

**Issue by peter-pakanun** [remcohaszing/monaco-yaml#234]
When autocomplete a string that start with `#` it get placed in without quote, making it a comment
![image](https://github.com/remcohaszing/monaco-yaml/assets/6493474/88b1eb87-b7f3-4b1a-98a5-a8f4961d3098)
![image](https://github.com/remcohaszing/monaco-yaml/assets/6493474/fb0a8c2c-58e0-4b15-83f8-6d39039dfae6)

Maybe check to see if the string start with `#` and put quote around it?
![image](https://github.com/remcohaszing/monaco-yaml/assets/6493474/0ffd016e-170a-4c17-a587-0ee45a7ce9b3)

**Comment by remcohaszing** [comment]
I agree. The proper solution IMO would be to serialize the value as YAML, so it handles any special consructs.

This is an upstream issue in [yaml-language-server](https://github.com/redhat-developer/yaml-language-server). Please report it with them. Once it’s fixed there and released, I will update `monaco-yaml`.
