### ISSUE TITLE
Uncaught (in promise) Error: Worker manager has been disposed

### ISSUE THREAD

**Issue by GopiAgasthia** [remcohaszing/monaco-yaml#235]
Using react-typescript with vite

```
const monacoYaml = configureMonacoYaml(monaco);
```
```
const setYamlTypeAhead = () => {
	monacoYaml.update({
		schemas: [
			{
				fileMatch: ['*'],
				schema: jsonSchema,
				uri: 'https://json-schema.org/draft/2020-12/schema',
			},
		],
	});
};
```

```
useEffect(() => {
	if (!editorRef.current) {
		return;
	}

	if (!codeEditorRef) {
		const language = isJsonMode ? 'json' : 'yaml';
		options.language = language;
		const model = monaco.editor.createModel(options.value || '', options.language);
		options.model = model;
		codeEditorRef = monaco.editor.create(editorRef.current, options);
		codeEditorRef.setValue(fileContent);
		if (isJsonMode){
			setJsonTypeAhead();
		} else {
			setYamlTypeAhead();
		}
	} 
	else {
		codeEditorRef.setValue(fileContent);
	}

	return () => {
		if (codeEditorRef) {
			codeEditorRef.dispose();
			monacoYaml?.dispose();
			codeEditorRef = null;
		}
	};
}, [isJsonMode]);
```
no issue on working, but getting console error in devtools
![image](https://github.com/remcohaszing/monaco-yaml/assets/69740917/bced0ad6-db9b-4377-9c3d-79fd3a563644)

**Comment by remcohaszing** [comment]
You should use `useEffect` to cleanup the side effects you triggered. `monacoYaml` isn’t created inside `useEffect`, you shouldn’t dispose it in `useEffect` either. You probably never need to dispose it.

**Comment by GopiAgasthia** [comment]
I got duplicate suggestions which is why I tried disposing monacoYaml, which solved the issue, is there any other way to solve the duplicates issue then

![image](https://github.com/remcohaszing/monaco-yaml/assets/69740917/b8cf1bea-2e33-4fd9-88c1-6f08b2d804bc)

**Comment by GopiAgasthia** [comment]
Nvm, 
```
monacoYaml?.update({schemas: []});
```
using this instead of dispose did the work
