### ISSUE TITLE
Missing this package “monaco-marker-data-provider”

### ISSUE THREAD

**Issue by caishengquan** [remcohaszing/monaco-yaml#239]
My project  Some old people
"@vue/cli-service": "4.4.4",
"monaco-editor": "^0.30.1",
"monaco-editor-webpack-plugin": "^6.0.0",
"monaco-yaml": "^4.0.2",
I encountered a problem while using it
“can't find monaco-marker-data-provider”

**Comment by remcohaszing** [comment]
I don’t understand your issue. Please provide a repo with a minimal reproduction.

All I can tell from your report is that some dependencies are outdated.

**Comment by caishengquan** [comment]
> I don’t understand your issue. Please provide a repo with a minimal reproduction.
> 
> All I can tell from your report is that some dependencies are outdated.

I switched to vite, but there were new issues
![1718964443764](https://github.com/remcohaszing/monaco-yaml/assets/68362712/a07f91e4-0b55-4f57-bcf7-c81cb32731ba)

**Comment by caishengquan** [comment]
> > I don’t understand your issue. Please provide a repo with a minimal reproduction.
> > All I can tell from your report is that some dependencies are outdated.
> 
> I switched to vite, but there were new issues ![1718964443764](https://private-user-images.githubusercontent.com/68362712/341727337-a07f91e4-0b55-4f57-bcf7-c81cb32731ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjY1NDgsIm5iZiI6MTcxODk2NjI0OCwicGF0aCI6Ii82ODM2MjcxMi8zNDE3MjczMzctYTA3ZjkxZTQtMGI1NS00ZjU3LWJjZjctYzgxY2IzMjczMWJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEwMzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzM4ZmY1ZGVjOTI5M2NjNDExNzMzODk0NzQ3NjdlMWFjNDQ1ODJkNDMzNjc4YzUzNzJjMTAyNmU3ZWVjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJO1SzMVPQUVBkfLBny1ha-by6Hgoxqrp-MFhkpo3Es)

**Comment by caishengquan** [comment]
> I don’t understand your issue. Please provide a repo with a minimal reproduction.
> 
> All I can tell from your report is that some dependencies are outdated.

https://stackblitz.com/edit/vitejs-vite-7dgi42?file=src%2FApp.vue
This is a reproduction link
Can you help me take a look? Thank you

**Comment by remcohaszing** [comment]
Your `MonacoEnvironment` should look like this:

```ts
// I’m not sure if the .js extensions matter for your specific setup
import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker.js?worker';
import YamlWorker from 'monaco-yaml/yaml.worker.js?worker';

window.MonacoEnvironment = {
  getWorker(_, label) {
    switch (label) {
      case 'editorWorkerService':
        return new EditorWorker();
      case 'yaml':
        return new YamlWorker();
      default:
        throw new Error(`Unknown label ${label}`);
    }
  }
};
```

This will make another error appear, but I don’t see what causes that.

**Comment by caishengquan** [comment]
> Your `MonacoEnvironment` should look like this:
> 
> ```ts
> // I’m not sure if the .js extensions matter for your specific setup
> import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker.js?worker';
> import YamlWorker from 'monaco-yaml/yaml.worker.js?worker';
> 
> window.MonacoEnvironment = {
>   getWorker(_, label) {
>     switch (label) {
>       case 'editorWorkerService':
>         return new EditorWorker();
>       case 'yaml':
>         return new YamlWorker();
>       default:
>         throw new Error(`Unknown label ${label}`);
>     }
>   }
> };
> ```
> 
> This will make another error appear, but I don’t see what causes that.

Do monaco-yaml have any requirements for the version of monaco-editor

**Comment by remcohaszing** [comment]
See https://github.com/remcohaszing/monaco-yaml/blob/main/package.json#L56

But the error that appears seems to he related to the build setup.

**Comment by caishengquan** [comment]
> 请参阅https://github.com/remcohaszing/monaco-yaml/blob/main/package.json#L56
> 
> 但出现的错误似乎与构建设置有关。
![1719195785814](https://github.com/remcohaszing/monaco-yaml/assets/68362712/d9fe9fed-dd36-461e-9f5b-38b7c43bee0b)
My problem has been solved
You mentioned here that.
I created a new file based on the example you provided to import it into the worker. When using it, simply import the newly created file
