### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by wenlei0617** [remcohaszing/monaco-yaml#245]
![image](https://github.com/user-attachments/assets/3cdf5559-056d-48cb-96d9-0bda4fffdf02)
![image](https://github.com/user-attachments/assets/f6a52ced-2ad2-4d91-a2e7-1c32af691311)

Some browsers do not yet support the use of the structuredClone method in workers, leading to a ReferenceError: structuredClone is not defined. It is recommended to replace it with cloneDeep from lodash for better compatibility.

**Comment by remcohaszing** [comment]
You’re using an old Chromium version. All major browsers have supported `structuredClone` for over 2 years now. If you must support older browsers, use a `structuredClone` polyfill. E.g.

```js
// custom-yaml.worker.js

import structuredClone from "@ungap/structured-clone";

if (!("structuredClone" in globalThis)) {
  self.structuredClone = structuredClone;
}

import 'monaco-yaml/yaml.worker.js'
```
