### ISSUE TITLE
x-enumNames doesn't seem supported

### ISSUE THREAD

**Issue by lostb1t** [remcohaszing/monaco-yaml#246]
I have a json schema that emits x-enumNames but they are not used in Monaco yaml. Is this a setting or just unsupported?

example

```
  "SectionStyle": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "portrait",
        "landscape"
      ],
      "enum": [
        0,
        1
      ]
    },
    ```

**Comment by remcohaszing** [comment]
I’ve never heard of `x-enumNames` before. Please explain what this is, and where it comes from with a link.

**Comment by lostb1t** [comment]
never mind this seems like a non standard. Thought it was part of the spec

**Comment by remcohaszing** [comment]
Perhaps you’re looking for `enumDescriptions` / `markdownEnumDescriptions`?
