### ISSUE TITLE
Is there support for a custom language?

### ISSUE THREAD

**Issue by natschz** [remcohaszing/monaco-yaml#257]
Hello!

We are currently trying to add support for the liquid templating language, this results in a `yaml.liquid` language.

But for this the monaco-yaml plugin won't work. :(

Is there a way we can register said language or what to do in that case?

**Comment by remcohaszing** [comment]
YAML is a **structural data** language. Liquid is a **text** templating language. You can’t use a text templating language and have a good UX for structural data. Static code analysis tools need to understand the syntax to analyze, but they can’t understand anything if the file needs pre-processing. Besides that the syntax alone provides a horrible user experience. I have maintained [Helm charts](https://helm.sh/docs/chart_template_guide/) in the past. That has been the most horrible text editing experience I’ve ever had. In YAML even indentation is relevant. Your users shouldn’t have to care about indentation spaces.

I strongly and kindly urge you to please, for the sake of your users, use a language that produces structural data, such as JavaScript, Python, Lua, Ruby, or whatever. JavaScript support is even builtin to Monaco editor.

So no, I don’t think this is a good use case to add support for passing custom languages.

If you do insist on using Liquid, you can try to find an existing Liquid language service to hook into Monaco editor. Feel free to use `monaco-yaml` for inspiration.

**Comment by remcohaszing** [comment]
> I appreciate your concerns, but I this is beyond my influence

I understand. I hope my feedback helps make a case anyway.

> There are also text editors and IDE's that handle it pretty well! ;)

Yes, these use specialized tooling (such as [VSCode Kubernetes Tools](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools)), not [YAML language server](https://github.com/redhat-developer/yaml-language-server) (on which `monaco-yaml` is based)

> Either way, the problem at hand is, that your plugin is hardcoded to the the YAML language. So maybe it would be possible to implement a option, that will allow users of specify the language? (this might not only be used to extend YAML with templating languages ;))

I just don’t see a convincing argument. If people want to support YAML, they can use the `yaml` language. If you think your liquid templates are similar enough to YAML, so can you. This feature wouldn’t be hard to implement, but I fear it’ll lead down a rabbit hole of new issues.

If you really feel like you need to support a custom language with `monaco-yaml`, feel free to fork or use something like [`patch-package`](https://github.com/ds300/patch-package).
