### ISSUE TITLE
Seeing a low-level `_BugIndicatingError: Model is disposed!`

### ISSUE THREAD

**Issue by Bwvolleyball** [remcohaszing/monaco-yaml#259]
We seem to be getting a very low-level error with this plugin, I can't tell if it's breaking anything, but it's creating a lot of noise in our logs.

```stacktrace
Uncaught (in promise) _BugIndicatingError: Model is disposed!
    at _a2._assertNotDisposed (chunk-PPHCT6NN.js?v=a8509331:22487:17)
    at _a2.getVersionId (chunk-PPHCT6NN.js?v=a8509331:22685:14)
    at doValidate (monaco-yaml.js?v=a8509331:630:29)
```

I think I see a way to fix this, but I wanted to create an issue as a discussion board if needed.

Hopefully PR coming soon.

**Comment by Bwvolleyball** [comment]
Continuing the thread - it looks like the error itself is already accounted for in this library, I think this is where we were seeing the bug come from?

https://github.com/remcohaszing/monaco-marker-data-provider/blob/d6204e779b881e7466b49fd9f19ad71771181584/src/monaco-marker-data-provider.ts#L70

**Comment by Bwvolleyball** [comment]
So, I think we just need to make sure it's using a new enough version of the `monaco-marker-data-provider` dependency?

**Comment by Bwvolleyball** [comment]
One last confirmation - I added this to our package.json, and the error went away!

```json
  "overrides": {
    "monaco-marker-data-provider": "^1.2.4"
  }
  ```

**Comment by remcohaszing** [comment]
Great! Now you can remove the override as you don’t need it. You just had to update your lockfile.
