### ISSUE TITLE
Add allowComments Support

### ISSUE THREAD

**Issue by Ansaal** [remcohaszing/monaco-yaml#28]
Hey,
thanks for your work!
I have a Use-Case, in which we are saving the yaml as tree in our database, so comments will vanish anyways.
jsonLanguage supports the allowComments option, which would be really helpfull to ban comments.
https://github.com/Microsoft/monaco-json/blob/master/src/monaco.d.ts

**Comment by yazaabed** [comment]
Thank you for your question. How do you read the final tree?

**Comment by Ansaal** [comment]
Oh we're using snakeyaml on our Java-Backend to parse the yaml. 
Since comments are deleted on saving, it would be nice to not let the users comment in the first place.

**Comment by yazaabed** [comment]
> Oh we're using snakeyaml on our Java-Backend to parse the yaml.
> Since comments are deleted on saving, it would be nice to not let the users comment in the first place.

I will check how we can implement this and do the same as JSON. Is the screenshot as you want? 
<img width="402" alt="Screen Shot 2020-08-09 at 7 26 37 PM" src="https://user-images.githubusercontent.com/8734097/89738089-482b1300-da76-11ea-806c-33e437625043.png">

**Comment by Ansaal** [comment]
Yes exactly like that. That would be great!

**Comment by yazaabed** [comment]
@Ansaal I tried to implemented what you requests, but sadly it is not supported from `yaml-ast-parser` which is the core of `yaml-language-server`. I will keep an eye if I can find a solution regarding this.

You can find the issue here: https://github.com/mulesoft-labs/yaml-ast-parser/issues/27

**Comment by remcohaszing** [comment]
I have decided to close this issue as a won’t fix. The goal of this project is to bring `yaml-language-server` features to Monaco editor. If `yaml-language-server` doesn’t support it, it’s out of scope for this project.

The following might help you get started to implement it in your own project:

```ts
import * as monaco from 'monaco-editor';
import { registerMarkerDataProvider } from 'monaco-marker-data-provider';
import { LineCounter, Parser } from 'yaml';
import { CollectionItem, SourceToken, Token } from 'yaml/dist/parse/cst';

registerMarkerDataProvider(monaco, 'yaml', {
  owner: 'yaml-comments',
  provideMarkerData(model) {
    const comments: SourceToken[] = [];
    const counter = new LineCounter();
    const parser = new Parser(counter.addNewLine);

    function processToken(token: CollectionItem | CollectionItem[] | Token | Token[]): void {
      if (!token) {
        return;
      }
      if (Array.isArray(token)) {
        for (const subtoken of token) {
          processToken(subtoken);
        }
        return;
      }
      if ('type' in token && token.type === 'comment') {
        comments.push(token);
        return;
      }
      if ('value' in token) {
        processToken(token.value);
      }
      if ('start' in token) {
        processToken(token.start);
      }
      if ('end' in token) {
        processToken(token.end);
      }
      if ('key' in token) {
        processToken(token.key);
      }
      if ('items' in token) {
        processToken(token.items);
      }
    }

    for (const token of parser.parse(model.getValue())) {
      processToken(token);
    }

    return comments.map((comment) => {
      const start = counter.linePos(comment.offset);
      const end = counter.linePos(comment.offset + comment.source.length);

      return {
        startLineNumber: start.line,
        startColumn: start.col,
        endLineNumber: end.line,
        endColumn: end.col,

        // Tweak these values to your liking.
        code: 'disallowComments',
        message: 'Comments will be stripped when saved',
        tags: [monaco.MarkerTag.Unnecessary],
        severity: monaco.MarkerSeverity.Hint,
        source: comment.source,
      };
    });
  },
});
```

You may run into some performance issues. To tackle that, this can be off-loaded to a worker using [`monaco-worker-manager`](https://github.com/remcohaszing/monaco-worker-manager).
