### ISSUE TITLE
Upgrade yaml-language-server to 0.14

### ISSUE THREAD

**Issue by yazaabed** [remcohaszing/monaco-yaml#39]
We will upgrade to the latest version of yaml-language-server after 24.12.2020 as it is the release date for them. There will be a lot of breaking changes as we will jump from 0.11 to 0.14 as 0.13 has some issues with autocompletion.

**Comment by anisite** [comment]
I've tried to upgrade myself to new yaml-language-server version, but I am too dumb... Anyone can help me?

**Comment by yazaabed** [comment]
https://github.com/remcohaszing/monaco-yaml/pull/88
